openapi: "3.0.3"
info:
  title: "Reader Service API"
  description: "Reader Service API. This is a simple service providing CRUD functionality for Reader meta data."
  version: "1.0.0"
servers:
  - url: "https://localhost:8099"
paths:
  /users:
    get:
      summary: "GET users"
      operationId: "getUsers"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST users"
      operationId: "saveUsers"
      responses:
        "200":
          description: "OK"
  /apartments:
    get:
      summary: "GET apartments"
      operationId: "getApartments"
      responses:
        "200":
          description: "OK"
    post:
      summary: "POST apartments"
      operationId: "createApartmentReader"
      responses:
        "200":
          description: "OK"
