zuul:
  routes:
    foos:
      path: /foos/**
      url: http://localhost:8081/spring-zuul-foos-resource/foos
    homeApplication:
      path: /home/**
      url: http://localhost:8080/api/0/
  sensitiveHeaders: Cookie,Set-Cookie
server:
  port: 8081