home:
  application.url: http://localhost:8081
  reader.url: http://localhost:8099
  gateway.customRoutes.reader:
    - /users/**

zuul:
  routes:
    homeApplication:
      path: /**
      url: ${home.application.url}
  sensitiveHeaders: Cookie,Set-Cookie
  forceOriginalQueryStringEncoding: true

server:
  port: ${PORT:8080}