version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    networks:
      - home_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  home-data-migration:
    depends_on:
      postgres:
        condition: service_healthy
    image: homeacademy/data-migration
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?user=postgres&password=password
    ports:
      - 5001:5001
    networks:
      - home_network

  home-application:
    image: homeacademy/home-application
    depends_on:
      home-data-migration:
        condition: service_completed_successfully
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    ports:
      - 8080:8080
    networks:
      - home_network

# home-reader:
#   image: homeacademy/home-reader
#   environment:
#     DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#   ports:
#     - 8082:8082
#   networks:
#     - home_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - home_network

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#        - 8082:8082
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#    networks:
#      - home_network

volumes:
    data: {}

networks:
  home_network:
    external: false
    name: home_network
    driver: bridge
